// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/Base/Button.vue')['default']
    Chip: typeof import('./src/components/Base/Chip.vue')['default']
    Input: typeof import('./src/components/Base/Input.vue')['default']
    Navigation: typeof import('./src/components/Navigation/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDialog: typeof import('./src/components/SearchDialog/index.vue')['default']
    SearchForm: typeof import('./src/components/SearchForm/index.vue')['default']
    SearchResult: typeof import('./src/components/SearchResult/index.vue')['default']
    TrackCard: typeof import('./src/components/TrackCard/index.vue')['default']
  }
}

export {}
